### ISSUE TITLE
压力测试

### ISSUE THREAD

**Issue by huhansan16** [agedcat/WebServer#2]
压力测试只能进行一次，第一次用了4000量测试，第二次测试用了5000，就陷入了死循环，之后显示连接服务器失败

**Comment by agedcat** [comment]
先看一下cpu是不是满了

**Comment by huhansan16** [comment]
CPU使用使用率正常，我先测试过了1000的连接量，结果正常，接着测试了7000连接量，可以正常连接但是QPS值异常低，接着测试了8k连接量，显示Connect to server failed. Aborting benchmark.另外就是想问一下为什么并发量上了1w后你readme文件显示QPS也降低了

**Comment by agedcat** [comment]
这个是性能瓶颈的问题吧   你可以试着自己排查下  然后优化一下
